#! /bin/sh
rm -rf /usr/local/etc/marbleconf/
mkdir -p /usr/local/etc/marbleconf/hadoop
mkdir -p /usr/local/etc/marbleconf/hbase
mkdir -p /usr/local/etc/marbleconf/pig
mkdir -p /usr/local/etc/marbleconf/hive

cp -a conf/cdh3.hadoop.asakusa/ /usr/local/etc/marbleconf/hadoop/
cp -a conf/cdh4.hbase/ /usr/local/etc/marbleconf/hbase/

cp -a conf.client/cdh3.hadoop.client/ /usr/local/etc/marbleconf/hadoop/
cp -a conf.client/cdh4.hbase/ /usr/local/etc/marbleconf/hbase/
cp -a conf.client/cdh4.pig/ /usr/local/etc/marbleconf/pig/
cp -a conf.client/cdh4.hive/ /usr/local/etc/marbleconf/hive/

