#! /bin/sh
sudo rm -rf /etc/hadoop/cdh3.*
sudo rm -rf /etc/hadoop/cdh4.*

sudo cp -a conf/cdh3.hadoop.terasort/ /etc/hadoop/
sudo cp -a conf/cdh3.hadoop.client/ /etc/hadoop/
sudo cp -a conf/cdh4.hadoop.mrv1/ /etc/hadoop/

sudo chmod -R a+r /etc/hadoop/
sudo chmod -R a-w/etc/hadoop/
